# Config variables
$modulesPath = $HOME/.config/hypr/modules
$binPath = $HOME/.local/bin
$mainMod = SUPER # Sets "Windows" key as main modifier
$shiftMod= SUPER SHIFT
# Default programs
$terminal = kitty
$fileManager = nautilus
$webBrowser = firefox
$emailClient = thunderbird
$menu = wofi -a --show drun

# Load modules
source = $modulesPath/autostart.conf
source = $modulesPath/monitors.conf
source = $modulesPath/input-devices.conf
source = $modulesPath/cursor.conf
source = $modulesPath/hyprland-theme.conf
source = $modulesPath/master-layout.conf
source = $modulesPath/keybindings.conf
source = $modulesPath/workspace-navigation.conf
source = $modulesPath/window-rules.conf
source = $modulesPath/misc.conf
