#
# Autostart
#

exec-once = $binPath/shell/low-bat-notification.sh
exec-once = hyprpaper & hypridle &
exec-once = waybar -c $HOME/.config/waybar/config-hyprland.jsonc
exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/libexec/hyprpolkitagent & dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP & xhost +local:

