#
# Master layout
#

master {
  # new_status = master
  mfact = 0.52
}

bind = $mainMod, M, layoutmsg, swapwithmaster
bind = $mainMod, H, layoutmsg, cycleprev
bind = $mainMod, K, layoutmsg, cycleprev
bind = $mainMod, J, layoutmsg, cyclenext
bind = $mainMod, L, layoutmsg, cyclenext
bind = $mainMod SHIFT, F, fullscreen, 1
bind = $mainMod SHIFT, L, resizeactive, 10 0
bind = $mainMod SHIFT, H, resizeactive, -10 0
bind = $mainMod SHIFT, K, resizeactive, 0 -10
bind = $mainMod SHIFT, J, resizeactive, 0 10

